# Generated by Django 6.0.6 on 2026-08-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reating',
            new_name='rating',
        ),
    ]
