# Generated by Django 6.0.6 on 2026-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_review_rating_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_will_you_learn',
            field=models.TextField(blank=True),
        ),
    ]
